/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-19 04:36:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.book;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class RoomChoice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1688615093270L));
    _jspx_dependants.put("jar:file:/C:/workspace/5_Server/semiProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>예약페이지</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header.css\"> <!-- 헤더 스타일 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/RoomChoice.css\">\r\n");
      out.write("    <!-- j쿼리  -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("    <!-- 폰트 -->\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/7bc7245179.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- 부트스트랩 -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 헤더  -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 예약부분 바디 -->\r\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/book/reservationFinal\" method=\"get\" onsubmit=\"return reservationValidate()\">\r\n");
      out.write("        <div class=\"C-reservation\">\r\n");
      out.write("            <div class=\"C-rsv-main\">\r\n");
      out.write("                <div class=\"C-rsv-main-text\">지점 / 객실 / 날짜 / 인원 선택</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"C-rsv-head\">\r\n");
      out.write("                <div class=\"C-choiceHotel\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        호텔선택\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <select name=\"C-hotel-choice\" id=\"C-hotel-choice\">\r\n");
      out.write("                            <option name=\"Hotel\" value=\"none\" selected>호텔을 선택해주세요</option>\r\n");
      out.write("                            <option name=\"Hotel\" id=\"Gangnam\" value=\"Gangnam\">K-호텔 강남점</option>\r\n");
      out.write("                            <option name=\"Hotel\" id=\"jongno\" value=\"jongno\">K-호텔 종로점</option>\r\n");
      out.write("                            <option name=\"Hotel\" id=\"dangsan\" value=\"dangsan\">K-호텔 당산점</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"C-choiceRoom\">\r\n");
      out.write("                    <div>객실선택</div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <select name=\"C-room-choice\" id=\"C-room-choice\">\r\n");
      out.write("                            <option name=\"Room\" value=\"none\" selected>객실을 선택해주세요</option>\r\n");
      out.write("                            <option name=\"Room\" id=\"Deluxe\" value=\"Deluxe\">Deluxe Room</option>\r\n");
      out.write("                            <option name=\"Room\" id=\"Standard\" value=\"Standard\">Standard Room</option>\r\n");
      out.write("                            <option name=\"Room\" id=\"Suite\" value=\"Suite\">suite Room</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"C-checkInOut\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        체크인\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input type=\"date\" name=\"C-checkInTime\" class=\"C-checkIn\" id=\"C-start\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"C-dateView\">\r\n");
      out.write("                    <div class=\"C-countdate\" id=\"C-countdate\">\r\n");
      out.write("                        0박\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"C-checkInOut\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        체크아웃\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input type=\"date\" name=\"C-checkOutTime\" class=\"C-checkOut\" id=\"C-end\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"C-CountPerson\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div>성인</div>\r\n");
      out.write("                        <div class=\"C-person\">\r\n");
      out.write("                            <button type=\"button\" id=\"C-Aminusbutton\">-</button>\r\n");
      out.write("                            <input type=\"text\" name=\"C-adult\" id=\"C-adult\" placeholder=\"0\">\r\n");
      out.write("                            <button type=\"button\" id=\"C-Aplusbutton\">+</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div>어린이</div>\r\n");
      out.write("                        <div class=\"C-person\">\r\n");
      out.write("                            <button type=\"button\" id=\"C-Cminusbutton\">-</button>\r\n");
      out.write("                            <input type=\"text\" name=\"C-children\" id=\"C-children\" placeholder=\"0\">\r\n");
      out.write("                            <button type=\"button\" id=\"C-Cplusbutton\">+</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"C-rsv-button\">\r\n");
      out.write("                    <button type=\"submit\" id=\"C-reservationBtn\">예약</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    <div class=\"accordion test\" id=\"accordionExample\" >\r\n");
      out.write("        <div class=\"accordion-item\">\r\n");
      out.write("            <h2 class=\"accordion-header\" id=\"headingOne\">\r\n");
      out.write("                <button class=\"accordion-button\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseOne\"\r\n");
      out.write("                    aria-expanded=\"true\" aria-controls=\"collapseOne\">\r\n");
      out.write("                    Deluxe Room\r\n");
      out.write("                </button>\r\n");
      out.write("            </h2>\r\n");
      out.write("            <div id=\"collapseOne\" class=\"accordion-collapse collapse show\" aria-labelledby=\"headingOne\"\r\n");
      out.write("                data-bs-parent=\"#accordionExample\">\r\n");
      out.write("                <div class=\"accordion-body\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/Deluxe-Room_1.jpg\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"C-room-text\">\r\n");
      out.write("                        <pre>\r\n");
      out.write("\r\n");
      out.write("            <strong>객실 서비스</strong>\r\n");
      out.write("\r\n");
      out.write("            - Auto Window 설치 \r\n");
      out.write("\r\n");
      out.write("            - 개인 욕실 및 Miracle Window 설치 \r\n");
      out.write("            \r\n");
      out.write("            - 자동 냉난방 시설\r\n");
      out.write("\r\n");
      out.write("            - 해외 방송 시청 및 무료 Wi-Fi 이용가능 \r\n");
      out.write("\r\n");
      out.write("            - 초고속 인터넷 \r\n");
      out.write("\r\n");
      out.write("            - 냉장고 겸용 미니바 \r\n");
      out.write("                    </pre>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <pre>\r\n");
      out.write("\r\n");
      out.write("            <strong>객실 어메니티</strong>\r\n");
      out.write("            \r\n");
      out.write("            - 49인치 UHD TV 냉장고 전자레인지 \r\n");
      out.write("\r\n");
      out.write("            - 구둣주걱 구두클리너 티포트 \r\n");
      out.write("            \r\n");
      out.write("            - 금고 미니바\r\n");
      out.write("\r\n");
      out.write("            - 욕실 목욕가운 비데 헤어드라이어\r\n");
      out.write("\r\n");
      out.write("                        </pre>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"accordion-item\">\r\n");
      out.write("            <h2 class=\"accordion-header\" id=\"headingTwo\">\r\n");
      out.write("                <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                    data-bs-target=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\">\r\n");
      out.write("                    Standard Room\r\n");
      out.write("                </button>\r\n");
      out.write("            </h2>\r\n");
      out.write("            <div id=\"collapseTwo\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingTwo\"\r\n");
      out.write("                data-bs-parent=\"#accordionExample\">\r\n");
      out.write("                <div class=\"accordion-body\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/standard-Room_1.jpg\" >\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"C-room-text\">\r\n");
      out.write("                        <pre>\r\n");
      out.write("\r\n");
      out.write("            <strong>객실 서비스</strong>\r\n");
      out.write("\r\n");
      out.write("            - Auto Window 설치 \r\n");
      out.write("\r\n");
      out.write("            - 개인 욕실 및 Miracle Window 설치 \r\n");
      out.write("            \r\n");
      out.write("            - 자동 냉난방 시설\r\n");
      out.write("\r\n");
      out.write("            - 해외 방송 시청 및 무료 Wi-Fi 이용가능 \r\n");
      out.write("\r\n");
      out.write("            - 초고속 인터넷 \r\n");
      out.write("\r\n");
      out.write("            - 냉장고 겸용 미니바 \r\n");
      out.write("                        </pre>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <pre>\r\n");
      out.write("\r\n");
      out.write("            <strong>객실 어메니티</strong>\r\n");
      out.write("            \r\n");
      out.write("            - 49인치 UHD TV 냉장고 전자레인지 \r\n");
      out.write("\r\n");
      out.write("            - 구둣주걱 구두클리너 티포트 \r\n");
      out.write("            \r\n");
      out.write("            - 금고 미니바\r\n");
      out.write("\r\n");
      out.write("            - 욕실 목욕가운 비데 헤어드라이어\r\n");
      out.write("\r\n");
      out.write("                        </pre>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"accordion-item\">\r\n");
      out.write("            <h2 class=\"accordion-header\" id=\"headingThree\">\r\n");
      out.write("                <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                    data-bs-target=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("                    Suite Room\r\n");
      out.write("                </button>\r\n");
      out.write("            </h2>\r\n");
      out.write("            <div id=\"collapseThree\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingThree\"\r\n");
      out.write("                data-bs-parent=\"#accordionExample\">\r\n");
      out.write("                <div class=\"accordion-body\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/suite-Room_1.jpg\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"C-room-text\">\r\n");
      out.write("                        <pre>\r\n");
      out.write("            <strong>객실 서비스</strong>\r\n");
      out.write("\r\n");
      out.write("            - Auto Window 설치 \r\n");
      out.write("\r\n");
      out.write("            - 개인 욕실 및 Miracle Window 설치 \r\n");
      out.write("            \r\n");
      out.write("            - 자동 냉난방 시설\r\n");
      out.write("\r\n");
      out.write("            - 해외 방송 시청 및 무료 Wi-Fi 이용가능 \r\n");
      out.write("\r\n");
      out.write("            - 초고속 인터넷 \r\n");
      out.write("\r\n");
      out.write("            - 냉장고 겸용 미니바 \r\n");
      out.write("                    </pre>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <pre>\r\n");
      out.write("\r\n");
      out.write("            <strong>객실 어메니티</strong>\r\n");
      out.write("            \r\n");
      out.write("            - 49인치 UHD TV 냉장고 전자레인지 \r\n");
      out.write("\r\n");
      out.write("            - 구둣주걱 구두클리너 티포트 \r\n");
      out.write("            \r\n");
      out.write("            - 금고 미니바\r\n");
      out.write("\r\n");
      out.write("            - 욕실 목욕가운 비데 헤어드라이어\r\n");
      out.write("\r\n");
      out.write("                    </pre>\r\n");
      out.write("\r\n");
      out.write("                    <div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/RoomChoice.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("        integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/header.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
